# Hardware configuration for the dev VM (Gnome Boxes / QEMU, x86_64).
# Regenerated by `nixos-generate-config` on the installed system: Calamares
# "Erase disk" produced a single btrfs partition (label `root`, whole disk)
# with subvolumes `nix` and `home`; the root subvolume is the btrfs default.
# The VM boots Legacy BIOS — no ESP exists, so there is no /boot entry.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bc4ce504-4a4a-4677-90f7-9c76442a2951";
    fsType = "btrfs";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/bc4ce504-4a4a-4677-90f7-9c76442a2951";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/bc4ce504-4a4a-4677-90f7-9c76442a2951";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
